/**
 * @file include/style_ccs.h
 * @brief PROJECT
 *
 * DESCRIPTION
 *
 * @author astrobyte
 * @date 2026-04-09
 * @license GNU General Public License
 * @copyright Copyright (c) 2026 kevin Leon
 * @contact kevinleon.morales@gmail.com
 */
#ifndef GHOSTLAYER_STYLE_CCS_H
#define GHOSTLAYER_STYLE_CCS_H

const char *stylesheet =
    "* {"
    "  font-family: \"JetBrains Mono\", \"Fira Code\", \"Source Code Pro\", \"SF Mono\", Menlo, Consolas, monospace;"
    "  color: #cdd6f4;"
    "}"
    "window, dialog, popover, box, grid, paned, viewport, scrolledwindow, stack {"
    "  background-color: #1e1e2e;"
    "}"
    "label {"
    "  color: #cdd6f4;"
    "}"
    "separator {"
    "  background-color: #313244;"
    "}"
    "toolbar {"
    "  background-color: #181825;"
    "  border-bottom: 1px solid #313244;"
    "  padding: 4px;"
    "}"
    "button, toolbutton button, menubutton {"
    "  background: #313244;"
    "  color: #cdd6f4;"
    "  border: 1px solid #45475a;"
    "  border-radius: 4px;"
    "  padding: 5px 8px;"
    "}"
    "button:hover, toolbutton button:hover, menubutton:hover {"
    "  background: #45475a;"
    "  border-color: #74c7ec;"
    "}"
    "button:active, button:checked, toolbutton button:active, toolbutton button:checked {"
    "  background: #89b4fa;"
    "  color: #11111b;"
    "  border-color: #89dceb;"
    "}"
    "entry, spinbutton, combobox, combobox box, textview, textview text {"
    "  background-color: #181825;"
    "  color: #cdd6f4;"
    "  border-color: #45475a;"
    "}"
    "entry:focus, spinbutton:focus, combobox:focus, textview:focus {"
    "  border-color: #89dceb;"
    "  box-shadow: inset 0 0 0 1px #89dceb;"
    "}"
    "selection, textview text selection, entry selection {"
    "  background-color: #89b4fa;"
    "  color: #11111b;"
    "}"
    "treeview, treeview.view {"
    "  background-color: #1e1e2e;"
    "  color: #cdd6f4;"
    "  border: 1px solid #313244;"
    "  grid-line-color: #313244;"
    "  tree-line-color: #45475a;"
    "}"
    "treeview header button {"
    "  background: #181825;"
    "  color: #bac2de;"
    "  border-color: #313244;"
    "  border-radius: 0;"
    "  padding: 6px;"
    "}"
    "treeview row, treeview.view cell {"
    "  border-color: #313244;"
    "  color: #cdd6f4;"
    "}"
    "treeview row:nth-child(even), treeview.view:nth-child(even) {"
    "  background-color: #1e1e2e;"
    "}"
    "treeview row:nth-child(odd), treeview.view:nth-child(odd) {"
    "  background-color: #181825;"
    "}"
    "treeview row:hover, treeview.view:hover {"
    "  background-color: #313244;"
    "  color: #cdd6f4;"
    "}"
    "treeview row:selected, treeview row:selected:focus, treeview.view:selected, treeview.view:selected:focus {"
    "  background-color: #89b4fa;"
    "  color: #11111b;"
    "}"
    "menu, menuitem, .menu, .context-menu {"
    "  background-color: #181825;"
    "  color: #cdd6f4;"
    "  border-color: #313244;"
    "}"
    "menuitem:hover, menuitem:selected {"
    "  background-color: #89b4fa;"
    "  color: #11111b;"
    "}"
    "progressbar trough {"
    "  background-color: #11111b;"
    "  border: 1px solid #313244;"
    "  border-radius: 4px;"
    "  min-height: 8px;"
    "}"
    "progressbar progress {"
    "  background: #74c7ec;"
    "  border: 1px solid #89dceb;"
    "  border-radius: 4px;"
    "  min-height: 8px;"
    "}"
    "progressbar text {"
    "  color: #cdd6f4;"
    "}"
    "scrollbar trough {"
    "  background-color: #181825;"
    "}"
    "scrollbar slider {"
    "  background-color: #45475a;"
    "  border-radius: 4px;"
    "  min-width: 8px;"
    "  min-height: 8px;"
    "}"
    "scrollbar slider:hover {"
    "  background-color: #89dceb;"
    "}"
    "#container_table, #packet_viewer, #packet_viewer_window, #intruder_window {"
    "  background-color: #1e1e2e;"
    "}"
    "#statusbar {"
    "  background-color: #181825;"
    "  border-top: 1px solid #313244;"
    "  color: #bac2de;"
    "}"
    "#hexdump_textview, #hexdump_textview text {"
    "  background-color: #11111b;"
    "  color: #cdd6f4;"
    "}";

#endif //GHOSTLAYER_STYLE_CCS_H
